{% set name = "cornac" %}
{% set version = "1.14.2" %}
{% set sha256 = "adf831c17be9d2bd83d4244a2027b1e279b05e9434a4438a28f1bedb96473861" %}
{% set build = 2 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py<35]
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - llvm-openmp  # [osx]
    - python
    - pip
    - cython
    - numpy
    # some models cimports scipy.linalg.cython_blas
    - scipy
  run:
    - llvm-openmp  # [osx]
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}
    - tqdm
    - powerlaw

test:
  imports:
    - cornac

about:
  home: https://cornac.preferred.ai/
  license: Apache-2.0
  license_file: LICENSE
  summary: A Comparative Framework for Multimodal Recommender Systems
  doc_url: https://cornac.readthedocs.io/en/latest/
  dev_url: https://github.com/PreferredAI/cornac

extra:
  recipe-maintainers:
    - tqtg
