{% set name = "cornac" %}
{% set version = "2.2.0" %}
{% set sha256 = "4f97605837a122d7fbfdd00b7efd8ed1c12c3732311133f80e9aedb77c956d1f" %}
{% set build = 1 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py<38]
  number: {{ build }}
  script:
    - {{ PYTHON }} setup.py build_ext -j{{ CPU_COUNT }}
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - scipy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - cython
    - pip
    - setuptools
    - numpy
    # some models cimports scipy.linalg.cython_blas
    - scipy
  run:
    - python
    - setuptools
    - {{ pin_compatible('scipy') }}
    - tqdm
    - powerlaw

test:
  imports:
    - cornac

about:
  home: https://cornac.preferred.ai/
  license: Apache-2.0
  license_file: LICENSE
  summary: A Comparative Framework for Multimodal Recommender Systems
  doc_url: https://cornac.readthedocs.io/en/latest/
  dev_url: https://github.com/PreferredAI/cornac

extra:
  recipe-maintainers:
    - tqtg
