{% set name = "cornac" %}
{% set version = "1.0.0" %}
{% set sha256 = "268f09e506dcb30433afc0b2f61a09271f5a9bcb527470a567a780c288c952c8" %}
{% set build = 0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py<35]
  number: {{ build }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - llvm-openmp  # [osx]
    - python
    - pip
    - cython
    - numpy
  run:
    - llvm-openmp  # [osx]
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - tqdm

test:
  imports:
    - cornac

about:
  home: https://cornac.preferred.ai/
  license: Apache-2.0 
  license_file: "LICENSE" 
  summary: A collection of recommendation algorithms and comparisons
  doc_url: https://cornac.readthedocs.io/en/latest/
  dev_url: https://github.com/PreferredAI/cornac

extra:
  recipe-maintainers:
    - tqtg 
